# Generated by Django 5.0.3 on 2024-06-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Userapp", "0006_myrefaral_date_referred"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
